version: "3"
services:

  traefik:
    image: traefik:v1.4
    ports:
      - "80:80"
      - "8080:8080"
    labels:
      traefik.enabled: "false"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.toml:/traefik.toml

  ipfs:
    image: ipfs/go-ipfs:release
    volumes:
      - /srv/ipfs/export:/export
      - /srv/ipfs/data:/data/ipfs

  ipfs-cluster:
    image: ipfs/ipfs-cluster:v0.1.0
    links:
      -  ipfs
    volumes:
      - /srv/ipfs-cluster:/data/ipfs-cluster

  geth:
    image: ethereum/client-go:stable
    command: |
      --datadir "/data"
      --keystore "/keystore"
      --syncmode light
      --rpc
      --rpcaddr 0.0.0.0
      --rpccorsdomain "null"
      --metrics
    volumes:
      - /srv/geth/data:/data
      - /srv/geth/keystore:/keystore

  cadvisor:
    image: google/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro

  prometheus-node-exporter:
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /etc/hostname:/etc/host_hostname
    command: |
      -collector.procfs /host/proc
      -collector.sysfs /host/sys
      -collector.filesystem.ignored-mount-points "^/(sys|proc|dev|host|etc)($$|/)"
      -collectors.enabled="conntrack,diskstats,entropy,filefd,filesystem,loadavg,mdadm,meminfo,netdev,netstat,stat,textfile,time,vmstat"

  prometheus-server:
    image: prom/prometheus
    links:
      - cadvisor
      - prometheus-node-exporter
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  
  grafana:
    image: grafana/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=secret
    links:
      - prometheus-server:prometheus
