debug = true
checkNewVersion = true
logLevel = "INFO"

[retry]

[web]
address = ":8080"

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "traefik.doubting.org"
watch = true
exposedbydefault = true

