version: "2.2"
services:

  partiy:
    image: parity/parity:stable
    command: |
      --base-path /data
      --mode active
      --auto-update all
      --release-track stable
      --port 30303
      --pruning fast
      --ui-port 8180
      --ui-interface 0.0.0.0
      --jsonrpc-port 8545
      --jsonrpc-interface 0.0.0.0
      --jsonrpc-hosts="all"
      --dapps-port 8080
      --dapps-interface 0.0.0.0
    ports:
      - "8180:8180"
      - "30303:30303"
      - "8545:8545"
    volumes:
      - /srv/parity:/data
    cpu_count: 3
    mem_limit: 4G

  cadvisor:
    image: google/cadvisor
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro

  prometheus-pushgateway:
    image: prom/pushgateway
    ports:
      - 9091:9091

  prometheus-node-exporter:
    image: prom/node-exporter
    ports:
      - 9100:9100
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /etc/hostname:/etc/host_hostname
    command: |
      -collector.procfs /host/proc
      -collector.sysfs /host/sys
      -collector.filesystem.ignored-mount-points "^/(sys|proc|dev|host|etc)($$|/)"
      -collectors.enabled="conntrack,diskstats,entropy,filefd,filesystem,loadavg,mdadm,meminfo,netdev,netstat,stat,textfile,time,vmstat"

  prometheus-server:
    image: prom/prometheus
    ports:
      - 9090:9090
    links:
      - cadvisor
      - prometheus-pushgateway
      - prometheus-node-exporter
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=secret
    links:
      - prometheus-server:prometheus
